version: '3.8'

services:
  api:
    build: .
    image: mc_checker_base
    command: npm run start:api
    env_file:
      - .env
    restart: unless-stopped
    expose:
      - "3019"

  bot:
    image: mc_checker_base
    command: npm run start:bot
    env_file:
      - .env
    environment:
      API_BASE_URL: "http://api:3019"
    depends_on:
      - api
    restart: unless-stopped